# Generated by Django 5.2.5 on 2025-08-14 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.URLField(max_length=2048)),
                ('custom_alias', models.SlugField(blank=True, help_text='Optional custom short code (letters, numbers, hyphens/underscores).', null=True, unique=True)),
                ('short_code', models.CharField(blank=True, editable=False, max_length=16, unique=True)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
